### ISSUE TITLE
Features roadmap

### ISSUE THREAD

**Issue by gotson** [gotson/komga#22]
Here is a list of upcoming features i would like to add to Komga.

If you would like to see a feature that is not part of the list, please open an issue.

#### Next

- [ ] full text search that can handle accented characters, and order results by relevance. (#24)
- [ ] read status for books, with possibility to manually mark as read/unread from the UI for a book or a whole series. (#25)

#### Backlog (in no particular order)

- [ ] show all the books in error with error details in one place (admin only) (#26)
- [ ] metadata management (#11)
- [ ] proper handling of the HTTP cache for thumbnails and pages. Those images should be cached until change. (#27)
- [ ] webreader. That would bring Komga at par with Ubooquity. (#28)
- [ ] move library management (add/delete, view path) to Server Settings
- [ ] add result page for search, when search results cannot fit all in the popup (#29)
- [ ] add ability to group Series into Collections. These will be used to group related items (same universe), or to curate lists (reading list, favorites). (#30)
- [ ] [Tachiyomi] use book numbers instead of list index for chapters (#32)
- [ ] [Tachiyomi] use new API endpoints `/books` (#31)
- [ ] [Tachiyomi] offer sorting options for Series (#33)

#### Done

- [x] show all books in the web UI, not just the ones in ready state (4909fb612c5235777ceaa46f72d584f34625186f)
- [x] hide full path of series/books to non-admin (in the API) (42d63919c57f50d6a49599e1dfd56feb3d1e7291)
- [x] add endpoint aliases so that all opds feed urls use the same base path `/opds` (37fa1d0719ee1edf7d7fcf76c392d0766e04e1a2)
- [x] backend performance enhancements ([v0.9.1](https://github.com/gotson/komga/releases/tag/v0.9.1))

**Comment by gotson** [comment]
I am closing this, it's easier to manage all requests as issues.
